#services:
#  app:
#    build: .
#    ports:
#      - "8080:8080"
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/constructcompany
#    depends_on:
#      - db
#  db:
#    image: postgres
#    environment:
#      - POSTGRES_PASSWORD=namnam123
#      - POSTGRES_DB=constructcompany
#    volumes:
#      - postgres-data:/var/lib/postgresql/data
#
#volumes:
#  postgres-data: